run:
  timeout: 3m
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/kweusuf/novel-qa-go
