services:
  novel-qa:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - novel_data:/app/novels
      - chroma_data:/app/chroma_db
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    restart: unless-stopped
    networks:
      - novel-qa-network

volumes:
  novel_data:
    driver: local
  chroma_data:
    driver: local

networks:
  novel-qa-network:
    driver: bridge

